class CategoryHandler {
  static List<String> allCategories = [
    'Drama',
    'Fairytale',
    'Fantasy',
    'Graphic novel',
    'Historical fiction',
    'Horror',
    'Mystery',
    'Paranormal romance',
    'Picture book',
    'Poetry',
    'Political thriller',
    'Romance',
    'Science fiction',
    'Short story',
    'Suspense',
    'Thriller',
    'Western',
    'Young adult',
    'True crime',
    'Travel',
    'Sports and leisure',
    'Self help',
    'Science',
    'Review',
    'True crime',
    'Textbook',
    'Religion, spirituality, and new age',
    'Prayer',
    'Philosophy',
    'Memoir',
    'Math',
    'Journal',
    'Humor',
    'Home and garden',
    'History',
    'Health/fitness',
    'Guide',
    'Encyclopedia',
    'Dictionary',
    'Diary',
    'Cookbook',
    'Crafts/hobbies',
    'Business/economics',
    'Biography',
    'Autobiography',
    'Art/architecture',
  ];
}
